---
title: "JSC370 Lab 12 Demo"
author: "Janis Joplin"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

This is my JSC370 Lab 12 website. Enjoy!

```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
source("process_starbucks_data.R")
sb_usa <- sb_locs |> filter(Country == "US")

sb_locs_state <- sb_usa |>
  rename(state = 'State/Province') |>
  group_by(state) |>
  summarize(n_stores = n())

# need state abbreviations
usa_pop_abbr <- 
  full_join(usa_pop, usa_states,
            by = join_by(state == State) 
            ) 
  
sb_locs_state <- full_join(sb_locs_state, usa_pop_abbr,
                           by = join_by(state == Abbreviation)
                           )
```


## Showcasing plots {.tabset}

### Figure 1

```{r, echo=FALSE, message=FALSE, warning=FALSE}
sb_nutr |>
  unnest_tokens(word, Item, token = "words") |>
  filter(word %in% topwords$word) |>
  plot_ly(
    x = ~Calories,
    y = ~`Carb. (g)`,
    z = ~`Protein (g)`,
    color = ~word,
    type = 'scatter3d',
    mode = 'markers',
    marker = list(size = 5)
  ) |>
  layout(
    title = "3D Scatterplot of Calories, Carbs, and Protein",
    scene = list(
      xaxis = list(title = "Calories"),
      yaxis = list(title = "Carbohydrates (g)"),
      zaxis = list(title = "Proein (g)")
    )
  )
```

### Figure 2

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Set up mapping details
set_map_details <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('steelblue')
)

# Make sure both maps are on the same color scale
shadeLimit <- 125

# Create hover text
sb_locs_state$hover <- with(sb_locs_state, paste("Number of Starbucks: ", n_stores, '<br>', "State: ", state.y, '<br>', "Population: ", population))

# Create the map
map1 <- plot_geo(sb_locs_state, locationmode = "USA-states") |>
  add_trace(z = ~n_stores, text = ~hover, locations = ~state,
            color = ~n_stores, colors = 'Purples') |>
  layout(title = "Starbucks store by state", geo = set_map_details)
map1
```
